// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CustomRepl: typeof import('./src/components/CustomRepl.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ICarbonLink: typeof import('~icons/carbon/link')['default']
    IEntypoSocialGithubWithCircle: typeof import('~icons/entypo-social/github-with-circle')['default']
    IEntypoSocialTwitterWithCircle: typeof import('~icons/entypo-social/twitter-with-circle')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Socials: typeof import('./src/components/Socials.vue')['default']
  }
}

export { }
