// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLink: typeof import('virtual:vite-icons/carbon/link')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RiMoonLine: typeof import('virtual:vite-icons/ri/moon-line')['default']
    RiSunLine: typeof import('virtual:vite-icons/ri/sun-line')['default']
  }
}

export { }
