/*
** TailwindCSS Configuration File
**
** Docs: https://tailwindcss.com/docs/configuration
** Default: https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js
*/
module.exports = {
  theme: {
    extend: {
      spacing: {
        96: '24rem'
      }
    }
  },
  variants: {
    accessibility: ['responsive', 'focus'],
    alignContent: ['responsive', 'hover', 'focus'],
    alignItems: ['responsive', 'hover', 'focus'],
    alignSelf: ['responsive', 'hover', 'focus'],
    appearance: ['responsive', 'hover', 'focus'],
    backgroundAttachment: ['responsive', 'hover', 'focus'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundOpacity: ['responsive', 'hover', 'focus'],
    backgroundPosition: ['responsive', 'hover', 'focus'],
    backgroundRepeat: ['responsive', 'hover', 'focus'],
    backgroundSize: ['responsive', 'hover', 'focus'],
    borderCollapse: ['responsive', 'hover', 'focus'],
    borderColor: ['responsive', 'hover', 'focus'],
    borderOpacity: ['responsive', 'hover', 'focus'],
    borderRadius: ['responsive', 'hover', 'focus'],
    borderStyle: ['responsive', 'hover', 'focus'],
    borderWidth: ['responsive', 'hover', 'focus'],
    boxShadow: ['responsive', 'hover', 'focus'],
    boxSizing: ['responsive', 'hover', 'focus'],
    clear: ['responsive', 'hover', 'focus'],
    cursor: ['responsive', 'hover', 'focus'],
    display: ['responsive', 'hover', 'focus'],
    divideColor: ['responsive', 'hover', 'focus'],
    divideOpacity: ['responsive', 'hover', 'focus'],
    divideWidth: ['responsive', 'hover', 'focus'],
    fill: ['responsive', 'hover', 'focus'],
    flex: ['responsive', 'hover', 'focus'],
    flexDirection: ['responsive', 'hover', 'focus'],
    flexGrow: ['responsive', 'hover', 'focus'],
    flexShrink: ['responsive', 'hover', 'focus'],
    flexWrap: ['responsive', 'hover', 'focus'],
    float: ['responsive', 'hover', 'focus'],
    fontFamily: ['responsive', 'hover', 'focus'],
    fontSize: ['responsive', 'hover', 'focus'],
    fontSmoothing: ['responsive', 'hover', 'focus'],
    fontStyle: ['responsive', 'hover', 'focus'],
    fontWeight: ['responsive', 'hover', 'focus'],
    gap: ['responsive', 'hover', 'focus'],
    gridAutoFlow: ['responsive', 'hover', 'focus'],
    gridColumn: ['responsive', 'hover', 'focus'],
    gridColumnEnd: ['responsive', 'hover', 'focus'],
    gridColumnStart: ['responsive', 'hover', 'focus'],
    gridRow: ['responsive', 'hover', 'focus'],
    gridRowEnd: ['responsive', 'hover', 'focus'],
    gridRowStart: ['responsive', 'hover', 'focus'],
    gridTemplateColumns: ['responsive', 'hover', 'focus'],
    gridTemplateRows: ['responsive', 'hover', 'focus'],
    height: ['responsive', 'hover', 'focus'],
    inset: ['responsive', 'hover', 'focus'],
    justifyContent: ['responsive', 'hover', 'focus'],
    letterSpacing: ['responsive', 'hover', 'focus'],
    lineHeight: ['responsive', 'hover', 'focus'],
    listStylePosition: ['responsive', 'hover', 'focus'],
    listStyleType: ['responsive', 'hover', 'focus'],
    margin: ['responsive', 'hover', 'focus'],
    maxHeight: ['responsive', 'hover', 'focus'],
    maxWidth: ['responsive', 'hover', 'focus'],
    minHeight: ['responsive', 'hover', 'focus'],
    minWidth: ['responsive', 'hover', 'focus'],
    objectFit: ['responsive', 'hover', 'focus'],
    objectPosition: ['responsive', 'hover', 'focus'],
    opacity: ['responsive', 'hover', 'focus'],
    order: ['responsive', 'hover', 'focus'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive', 'hover', 'focus'],
    padding: ['responsive', 'hover', 'focus'],
    placeholderColor: ['responsive', 'focus'],
    placeholderOpacity: ['responsive', 'focus'],
    pointerEvents: ['responsive', 'hover', 'focus'],
    position: ['responsive', 'hover', 'focus'],
    resize: ['responsive', 'hover', 'focus'],
    rotate: ['responsive', 'hover', 'focus'],
    scale: ['responsive', 'hover', 'focus'],
    skew: ['responsive', 'hover', 'focus'],
    space: ['responsive', 'hover', 'focus'],
    stroke: ['responsive', 'hover', 'focus'],
    strokeWidth: ['responsive', 'hover', 'focus'],
    tableLayout: ['responsive', 'hover', 'focus'],
    textAlign: ['responsive', 'hover', 'focus'],
    textColor: ['responsive', 'hover', 'focus'],
    textDecoration: ['responsive', 'hover', 'focus'],
    textOpacity: ['responsive', 'hover', 'focus'],
    textTransform: ['responsive', 'hover', 'focus'],
    transform: ['responsive', 'hover', 'focus'],
    transformOrigin: ['responsive', 'hover', 'focus'],
    transitionDelay: ['responsive', 'hover', 'focus'],
    transitionDuration: ['responsive', 'hover', 'focus'],
    transitionProperty: ['responsive', 'hover', 'focus'],
    transitionTimingFunction: ['responsive', 'hover', 'focus'],
    translate: ['responsive', 'hover', 'focus'],
    userSelect: ['responsive', 'hover', 'focus'],
    verticalAlign: ['responsive', 'hover', 'focus'],
    visibility: ['responsive', 'hover', 'focus'],
    whitespace: ['responsive', 'hover', 'focus'],
    width: ['responsive', 'hover', 'focus'],
    wordBreak: ['responsive', 'hover', 'focus'],
    zIndex: ['responsive', 'hover', 'focus']
  },
  plugins: [],
  purge: false
}
